# /etc/kubernetes/manifests/kube-apiserver.yaml - change to correct ca file
# ~/.kube/config - change to correct port
# kubectl edit deployments coredns  -n kube-system - change to correct image
# kubectl uncordon node01
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/web"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: data-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    run: gop-fileserver
spec:
  containers:
    - name: gop-fileserver
      image: kodekloud/fileserver
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      volumeMounts:
        - mountPath: "/web"
          name: data-store
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector:
    run: gop-fileserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
